=== leoninnovate/cs6340/Assignment7/asgn7/analysis/schemes.dtd
<!ELEMENT schemes (scheme*)>

<!ELEMENT scheme (predicate+)>
<!ATTLIST scheme
  id ID #REQUIRED
>

<!ELEMENT predicate EMPTY>
<!ATTLIST predicate
  text CDATA #REQUIRED
>

=== leoninnovate/cs6340/Assignment7/asgn7/analysis/schemes.xml
<?xml version="1.0"?>
<!DOCTYPE schemes SYSTEM "schemes.dtd">

<schemes>
  <scheme id="branches">
    <predicate text="is FALSE"/>
    <predicate text="is TRUE"/>
  </scheme>
  <scheme id="g-object-unref">
    <predicate text="== 0"/>
    <predicate text="!= 0"/>
    <predicate text="== 1"/>
    <predicate text="!= 1"/>
    <predicate text="&gt; 1"/>
    <predicate text="&lt;= 1"/>
    <predicate text="is invalid"/>
    <predicate text="is valid"/>
  </scheme>
  <scheme id="returns">
    <predicate text="&lt;"/>
    <predicate text="&gt;="/>
    <predicate text="=="/>
    <predicate text="!="/>
    <predicate text="&gt;"/>
    <predicate text="&lt;="/>
  </scheme>
  <scheme id="scalar-pairs">
    <predicate text="&lt;"/>
    <predicate text="&gt;="/>
    <predicate text="=="/>
    <predicate text="!="/>
    <predicate text="&gt;"/>
    <predicate text="&lt;="/>
  </scheme>
</schemes>
