=== leoninnovate/cs6340/Assignment7/asgn7/analysis/summary.dtd
<!-- results from a single experiment -->
<!ELEMENT experiment (runs, analysis, schemes)>
<!ATTLIST experiment
  date CDATA #REQUIRED
  source-dir CDATA #IMPLIED>

<!-- outcome summary for the runs in an experiment -->
<!ELEMENT runs EMPTY>
<!ATTLIST runs success NMTOKEN #REQUIRED>
<!ATTLIST runs failure NMTOKEN #REQUIRED>
<!ATTLIST runs ignore NMTOKEN #REQUIRED>

<!-- data analysis parameters -->
<!ELEMENT analysis EMPTY>
<!ATTLIST analysis confidence NMTOKEN #REQUIRED>

<!-- list of instrumentation schemes -->
<!ELEMENT schemes (scheme+)>

<!-- names and predicate counts for one scheme -->
<!ELEMENT scheme EMPTY>
<!ATTLIST scheme name CDATA #REQUIRED>
<!ATTLIST scheme total NMTOKEN #REQUIRED>
<!ATTLIST scheme retain NMTOKEN #REQUIRED>

=== leoninnovate/cs6340/Assignment7/asgn7/analysis/summary.xml
<?xml version="1.0"?><?xml-stylesheet type="text/xsl" href="summary.xsl"?><!DOCTYPE experiment SYSTEM "summary.dtd"><experiment date="Wed Apr 20 10:51:03 2005
" source-dir="src"><runs success="620" failure="180" ignore="0"/><analysis confidence="95"/><schemes><scheme name="branches" total="2838" retain="11"/><scheme name="returns" total="2430" retain="5"/><scheme name="scalar-pairs" total="57102" retain="17"/><scheme name="g-object-unref" total="0" retain="0"/></schemes></experiment>
